### ISSUE TITLE
プッシュに失敗する

### ISSUE THREAD

**Issue by 5GHzShiro** [YutoFuse/CalendarApp#11]
AndroidStudio内のターミナル上でgit commit実行後、git pushを実行すると以下のような文章が出てきてpushできているのかが不明な状態に陥りました。
エラー文最後の行に依れば、認証エラーを起こしているようです。
こちらのidパスワードは間違っていないはずなので...一応そちらでも、僕がプッシュできる設定になっているかどうか(?)の確認をよろしくお願いいたします。
(base) absolute-zero@oosunayoshikinoMacBook-Pro CalendarApp % git push origin InsertImages
Username for 'https://github.com': 5GHzShiro
Password for 'https://5GHzShiro@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/YutoFuse/CalendarApp.git/'

**Comment by YutoFuse** [comment]
@5GHzShiro 
こちら確認してみてください。
https://qiita.com/mkato1013/items/86040c5e0317951cfaef

**Comment by 5GHzShiro** [comment]
ありがとうございます、クラシックの方のトークンをrepoで発行して行けたと思います、pushできているか確認よろしくお願いいたします。

**Comment by YutoFuse** [comment]
issueが完了したら画面下にあるCloseで閉じておいてください。

**Comment by 5GHzShiro** [comment]
あ、失礼しました了解です
